import { describe, expect, it } from 'vitest'
import { importSlicerConfig } from '../../../src/engine/pa/slicerImport'

const prusaFlat = `# generated by PrusaSlicer 2.7.4 on 2026-01-01 at 12:00:00 UTC
bed_shape = 5x5,305x5,305x305,5x305
nozzle_diameter = 0.4
filament_diameter = 1.75
first_layer_temperature = 215
temperature = 210
first_layer_bed_temperature = 65
bed_temperature = 60
layer_height = 0.2
first_layer_height = 75%
retract_length = 0.8
retract_speed = 35
travel_speed = 180
default_acceleration = 0
machine_max_acceleration_extruding = 1500,960
machine_max_acceleration_x = 4000,960
machine_max_jerk_x = 8,8
start_gcode = G28 ; home all\\nG90\\nM83
end_gcode = M104 S0\\nM84
filament_type = PETG
gcode_flavor = klipper
`

const prusaBundle = `# generated by PrusaSlicer 2.7.4
[print:*common*]
layer_height = 0.25
travel_speed = 120

[print:0.20mm QUALITY]
layer_height = 0.2
travel_speed = 150
default_acceleration = 1250

[filament:Prusament PLA]
filament_type = PLA
temperature = 215
first_layer_temperature = 220
filament_diameter = 1.75
bed_temperature = 60

[printer:Original Prusa MK4]
bed_shape = 0x0,250x0,250x210,0x210
nozzle_diameter = 0.4
gcode_flavor = marlin2
machine_max_jerk_x = 8
machine_max_acceleration_extruding = 4000
retract_length = 0.7
retract_speed = 40
start_gcode = G28\\nG1 Z5
end_gcode = M84

[presets]
print = 0.20mm QUALITY
filament = Prusament PLA
printer = Original Prusa MK4
`

const orcaMachine = JSON.stringify({
  type: 'machine',
  name: 'My Voron 0.4 nozzle',
  from: 'user',
  version: '1.9.0.0',
  printable_area: ['0x0', '350x0', '350x350', '0x350'],
  nozzle_diameter: ['0.4'],
  gcode_flavor: 'klipper',
  retraction_length: ['0.5'],
  retraction_speed: ['40'],
  machine_max_acceleration_extruding: ['7000', '7000'],
  machine_max_jerk_x: ['9', '9'],
  machine_start_gcode: 'PRINT_START\nG28',
  machine_end_gcode: 'PRINT_END',
  machine_pause_gcode: 'PAUSE',
})

const orcaFilament = JSON.stringify({
  type: 'filament',
  name: 'PLA Basic @Voron',
  from: 'user',
  inherits: 'fdm_filament_pla',
  filament_diameter: ['1.75'],
  nozzle_temperature: ['220'],
  nozzle_temperature_initial_layer: ['215'],
  cool_plate_temp: ['0'],
  cool_plate_temp_initial_layer: ['0'],
  hot_plate_temp: ['60'],
  hot_plate_temp_initial_layer: ['65'],
  textured_plate_temp: ['55'],
  chamber_temperatures: ['0'],
  filament_type: ['PLA'],
  filament_retraction_length: ['nil'],
  filament_retraction_speed: ['nil'],
})

describe('importSlicerConfig with a flat PrusaSlicer export', () => {
  const result = importSlicerConfig('config.ini', prusaFlat)

  it('reads the bed size from the bed_shape polygon bounding box', () => {
    expect(result.fields.bedWidthMm).toBe(300)
    expect(result.fields.bedDepthMm).toBe(300)
  })

  it('takes index 0 of per-extruder comma lists', () => {
    expect(result.fields.nozzleDiameterMm).toBe(0.4)
    expect(result.fields.retractMm).toBe(0.8)
    expect(result.fields.retractSpeedMmS).toBe(35)
  })

  it('prefers first-layer temperatures', () => {
    expect(result.fields.nozzleTempC).toBe(215)
    expect(result.fields.bedTempC).toBe(65)
  })

  it('reads the plain scalar keys', () => {
    expect(result.fields.filamentDiameterMm).toBe(1.75)
    expect(result.fields.layerHeightMm).toBe(0.2)
    expect(result.fields.travelSpeedMmS).toBe(180)
    expect(result.fields.filamentType).toBe('PETG')
  })

  it('falls back to machine_max_acceleration_extruding when default_acceleration is 0, taking the normal value of a dual pair', () => {
    expect(result.fields.printAccelMmS2).toBe(1500)
  })

  it('maps machine_max_jerk_x to square corner velocity', () => {
    expect(result.fields.squareCornerVelocityMmS).toBe(8)
  })

  it('unescapes literal backslash-n in gcode', () => {
    expect(result.fields.startGcode).toBe('G28 ; home all\nG90\nM83')
    expect(result.fields.endGcode).toBe('M104 S0\nM84')
  })

  it('maps klipper gcode_flavor to Klipper firmware', () => {
    expect(result.fields.firmware).toBe('Klipper')
  })

  it('reports imported and missing field lists', () => {
    expect(result.imported).toContain('bedWidthMm')
    expect(result.imported).toContain('startGcode')
    expect(result.imported).not.toContain('pauseGcode')
    expect(result.missing).toContain('pauseGcode')
    expect(result.missing).toContain('chamberTempC')
    expect(result.missing).not.toContain('bedTempC')
    expect(result.warnings).toEqual([])
  })
})

describe('importSlicerConfig Prusa edge cases', () => {
  it('skips percent values with a warning', () => {
    const result = importSlicerConfig('config.ini', 'layer_height = 75%\ntravel_speed = 150\n')
    expect(result.fields.layerHeightMm).toBeUndefined()
    expect(result.missing).toContain('layerHeightMm')
    expect(result.warnings.some((w) => w.includes('75%'))).toBe(true)
    expect(result.fields.travelSpeedMmS).toBe(150)
  })

  it('warns on an unknown gcode_flavor and leaves firmware unset', () => {
    const result = importSlicerConfig('config.ini', 'gcode_flavor = sailfish\n')
    expect(result.fields.firmware).toBeUndefined()
    expect(result.missing).toContain('firmware')
    expect(result.warnings.some((w) => w.includes('sailfish'))).toBe(true)
  })

  it('falls back to non-first-layer temperatures', () => {
    const result = importSlicerConfig('config.ini', 'temperature = 240\nbed_temperature = 85\n')
    expect(result.fields.nozzleTempC).toBe(240)
    expect(result.fields.bedTempC).toBe(85)
  })

  it('uses default_acceleration when it is nonzero', () => {
    const result = importSlicerConfig(
      'config.ini',
      'default_acceleration = 2000\nmachine_max_acceleration_extruding = 7000\n',
    )
    expect(result.fields.printAccelMmS2).toBe(2000)
  })
})

describe('importSlicerConfig with a PrusaSlicer bundle', () => {
  const result = importSlicerConfig('bundle.ini', prusaBundle)

  it('uses the presets named in [presets], not hidden *common* presets', () => {
    expect(result.fields.layerHeightMm).toBe(0.2)
    expect(result.fields.travelSpeedMmS).toBe(150)
  })

  it('merges printer, filament, and print sections', () => {
    expect(result.fields.bedWidthMm).toBe(250)
    expect(result.fields.bedDepthMm).toBe(210)
    expect(result.fields.nozzleTempC).toBe(220)
    expect(result.fields.filamentType).toBe('PLA')
    expect(result.fields.retractMm).toBe(0.7)
    expect(result.fields.printAccelMmS2).toBe(1250)
    expect(result.fields.startGcode).toBe('G28\nG1 Z5')
  })

  it('maps marlin2 to Marlin', () => {
    expect(result.fields.firmware).toBe('Marlin')
  })

  it('falls back to the first non-hidden preset per section when [presets] is absent', () => {
    const noPresets = prusaBundle.replace(/\[presets\][\s\S]*$/, '')
    const r = importSlicerConfig('bundle.ini', noPresets)
    expect(r.fields.layerHeightMm).toBe(0.2)
    expect(r.fields.bedWidthMm).toBe(250)
  })
})

describe('importSlicerConfig with an OrcaSlicer machine preset', () => {
  const result = importSlicerConfig('My Voron 0.4 nozzle.json', orcaMachine)

  it('reads the bed size from the printable_area polygon', () => {
    expect(result.fields.bedWidthMm).toBe(350)
    expect(result.fields.bedDepthMm).toBe(350)
  })

  it('takes element 0 of string arrays', () => {
    expect(result.fields.nozzleDiameterMm).toBe(0.4)
    expect(result.fields.retractMm).toBe(0.5)
    expect(result.fields.retractSpeedMmS).toBe(40)
    expect(result.fields.printAccelMmS2).toBe(7000)
    expect(result.fields.squareCornerVelocityMmS).toBe(9)
  })

  it('reads machine gcode with real newlines and the pause gcode', () => {
    expect(result.fields.startGcode).toBe('PRINT_START\nG28')
    expect(result.fields.endGcode).toBe('PRINT_END')
    expect(result.fields.pauseGcode).toBe('PAUSE')
  })

  it('maps the firmware and reports filament fields as missing', () => {
    expect(result.fields.firmware).toBe('Klipper')
    expect(result.missing).toContain('filamentDiameterMm')
    expect(result.missing).toContain('nozzleTempC')
    expect(result.missing).toContain('filamentType')
    expect(result.warnings).toEqual([])
  })
})

describe('importSlicerConfig with an OrcaSlicer filament preset', () => {
  const result = importSlicerConfig('PLA Basic.json', orcaFilament)

  it('prefers the initial-layer nozzle temperature', () => {
    expect(result.fields.nozzleTempC).toBe(215)
  })

  it('prefers the hot plate initial-layer temperature for the bed', () => {
    expect(result.fields.bedTempC).toBe(65)
  })

  it('reads chamber temperature, filament type, and diameter', () => {
    expect(result.fields.chamberTempC).toBe(0)
    expect(result.fields.filamentType).toBe('PLA')
    expect(result.fields.filamentDiameterMm).toBe(1.75)
  })

  it('treats "nil" entries as absent', () => {
    expect(result.fields.retractMm).toBeUndefined()
    expect(result.missing).toContain('retractMm')
  })

  it('warns about inheritance because the preset carries inherits', () => {
    expect(result.warnings.some((w) => w.toLowerCase().includes('inherit'))).toBe(true)
  })
})

describe('importSlicerConfig with a sparse Orca preset that inherits', () => {
  it('imports what is present and warns about the system parent', () => {
    const sparse = JSON.stringify({
      type: 'process',
      name: '0.20mm mine',
      inherits: '0.20mm Standard @BBL X1C',
      layer_height: '0.2',
    })
    const result = importSlicerConfig('process.json', sparse)
    expect(result.fields.layerHeightMm).toBe(0.2)
    expect(result.imported).toEqual(['layerHeightMm'])
    expect(result.warnings.some((w) => w.toLowerCase().includes('inherit'))).toBe(true)
  })
})

describe('importSlicerConfig with unusable content', () => {
  it('throws a user-worded error on content that is neither JSON nor INI-like', () => {
    expect(() => importSlicerConfig('photo.txt', 'PK not a config at all')).toThrow(
      /does not look like/i,
    )
  })
})
